src/server/master/web_ui/application/web_ui/docs/urls.py
from django.conf.urls.defaults import *

from templatetags.wiki import WIKI_WORD


urlpatterns = patterns('docs.views',
    (r'^$', 'index'),
    ('overview.html', 'index'),
    ('(?P<name>%s)/$' % WIKI_WORD, 'view'),
    ('(?P<name>%s)/edit/$' % WIKI_WORD, 'edit'),
)

src/server/master/web_ui/application/web_ui/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = patterns('',
    (r'^$', 'web_ui.main.views.index.index'),
    (r'^pricing$',                  'web_ui.main.views.index.pricing'),
    # Log in/log out/request password reset
    (r'^login$',                  'web_ui.main.views.login_logout.login'),
    (r'^logout$',                 'web_ui.main.views.login_logout.logout'),
    (r'^request_reset_password$', 'web_ui.main.views.login_logout.request_reset_password'),
    (r'^reset_password$', 'web_ui.main.views.login_logout.reset_password'),
    (r'^set_password$', 'web_ui.main.views.login_logout.set_password'),
    # Request account/create account using invite code
    (r'^signup$',     'web_ui.main.views.create_account.signup'),
    (r'^join$',       'web_ui.main.views.create_account.join'),
    (r'^hackerdojo$', 'web_ui.main.views.create_account.hackerdojo'),
    # Administrative dashboard
    (r'^admin$',        'web_ui.main.views.admin.admin'),
    (r'^admin/invite$', 'web_ui.main.views.admin.invite'),
    (r'^admin/get_emails$', 'web_ui.main.views.admin.get_emails'),
    # User dashboard
    (r'^dashboard$',                                                             'web_ui.main.views.dashboard_applicationlist.applicationlist'),
    (r'^dashboard/account$',                                                     'web_ui.main.views.dashboard_account.account'),
    (r'^dashboard/account/change_password$',                                     'web_ui.main.views.dashboard_account.change_password'),
    (r'^dashboard/account/change_email$',                                        'web_ui.main.views.dashboard_account.change_email'),
    (r'^dashboard/account/add_ssh_public_key$',                                  'web_ui.main.views.dashboard_account.add_ssh_public_key'),
    (r'^dashboard/account/remove_ssh_public_key$',                               'web_ui.main.views.dashboard_account.remove_ssh_public_key'),
    (r'^dashboard/invite$',                                                      'web_ui.main.views.dashboard_invite.invite'),
    (r'^dashboard/application/(?P<application_name>[^/]*)$',                     'web_ui.main.views.dashboard_application.application'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/allocation$',          'web_ui.main.views.dashboard_application.application_allocation_redirect'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/add_domain$',          'web_ui.main.views.dashboard_application.add_domain_redirect'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/remove_domain$',       'web_ui.main.views.dashboard_application.remove_domain_redirect'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/debug$',               'web_ui.main.views.dashboard_application.debug_redirect'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/server_cache$',        'web_ui.main.views.dashboard_application.server_cache_redirect'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/logs$',                'web_ui.main.views.dashboard_application.logs'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/add_collaborator$',    'web_ui.main.views.dashboard_application.add_collaborator'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/remove_collaborator$', 'web_ui.main.views.dashboard_application.remove_collaborator'),
    (r'^dashboard/application/(?P<application_name>[^/]*)/delete$',              'web_ui.main.views.dashboard_application.delete_application'),
    (r'^dashboard/billing$',                                                     'web_ui.main.views.dashboard_billing.update_billing_info'),
    # Documentation
    (r'^docs/', include('docs.urls')),
    # Static content -- note, we should run web_ui as a djangy application since we're using static.serve
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'static'}),
)

src/server/master/web_ui/application/web_ui/docs/models.py
from django.db import models

from templatetags.wiki import wikify


class Page(models.Model):
    name = models.CharField(max_length=255, unique=True)
    content = models.TextField()
    rendered = models.TextField()

    class Meta:
        ordering = ('name', )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.rendered = wikify(self.content)
        super(Page, self).save(*args, **kwargs)

src/server/master/web_ui/application/web_ui/docs/forms.py
from django import forms as forms

from models import Page


class PageForm(forms.Form):
    name = forms.CharField(max_length=255)
    content = forms.CharField(widget=forms.Textarea(attrs={
        'cols':80,
        'rows':30
        }))

    def clean_name(self):
        import re
        from templatetags.wiki import WIKI_WORD

        pattern = re.compile(WIKI_WORD)

        name = self.cleaned_data['name']
        if not pattern.match(name):
            raise forms.ValidationError('Must be a WikiWord.')

        return name

src/server/master/web_ui/application/web_ui/docs/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from main.views.shared import is_admin, get_user, auth_required, admin_required
from forms import PageForm
from models import Page

def index(request):
    return HttpResponseRedirect('/docs/Documentation')

def view(request, name):
    """Shows a single wiki page."""
    try:
        page = Page.objects.get(name=name)
    except Page.DoesNotExist:
        page = Page(name=name)

    return render_to_response('wiki/view.html', {
        'page': page, 
        'admin': is_admin(request),
        'user': get_user(request),
        'navbar':Page.objects.get(name='NavBar'),
    })

@auth_required
@admin_required
def edit(request, name):
    """Allows users to edit wiki pages."""
    try:
        page = Page.objects.get(name=name)
    except Page.DoesNotExist:
        page = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if not page:
                page = Page()
            page.name = form.cleaned_data['name']
            page.content = form.cleaned_data['content']

            page.save()
            return HttpResponseRedirect('../../%s/' % page.name)
    else:
        if page:
            form = PageForm(initial=page.__dict__)
        else:
            form = PageForm(initial={'name': name})

    return render_to_response('wiki/edit.html', {
        'form': form, 
        'admin': is_admin(request),
        'user': get_user(request),
        'navbar':Page.objects.get(name='NavBar'),
    })

src/server/master/web_ui/application/web_ui/docs/templates/wiki/edit.html
{% extends 'wiki/wiki_base.html' %}


{% block wiki_content %}
	<h1>Edit</h1>

	<form action="" method="post">

		<div class="field_wrapper required{% if form.name.errors %} errors{% endif %}" id="field_name">
			<label for="id_name" class="field_name"><strong>Page name</strong></label>
			{% if form.name.errors %}{{ form.name.errors }}{% endif %}
			<div class="field text_input">
				{{ form.name }}
			</div>
		</div>

		<div class="field_wrapper required{% if form.content.errors %} errors{% endif %}" id="field_content">
			<label for="id_content" class="field_name"><strong>Content</strong></label>
			{% if form.content.errors %}{{ form.content.errors }}{% endif %}
			<div class="field textarea">
				{{ form.content }}
			</div>
		</div>

		<div class="submit">
			<input type="submit" value="Save" />
		</div>

	</form>
{% endblock %}

src/server/master/web_ui/application/web_ui/docs/templates/wiki/index.html
{% extends 'wiki/wiki_base.html' %}


{% block wiki_content %}
	<h1>Index</h1>

	{% if pages %}
		<ul>
			{% for page in pages %}
				<li><a href="{{ page.name }}/">{{ page.name }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p><a href="NewPage/edit/">Create a new page</a>.</p>
	{% endif %}
{% endblock %}

src/server/master/web_ui/application/web_ui/docs/templates/wiki/view.html
{% extends 'wiki/wiki_base.html' %}


{% block wiki_content %}
	{% comment %}
    <h1><a href="../{{ page.name }}/" rel="bookmark">{{ page.name }}</a></h1>
    {% endcomment %}
	{% if not page.id %}
        {% if admin %}
		<p>This page does not exist, <a href="edit/">create it now</a>?</p>
        {% endif %}
	{% endif %}

	{{ page.content|safe }}
{% endblock %}


{% block footer %}
    {% if admin %}
	{% if page.id %}
		<a href="edit/">Edit this page</a>
	{% else %}
		<a href="edit/">Create this page</a>
	{% endif %}
    {% endif %}
{% endblock %}

src/server/master/web_ui/application/web_ui/docs/templates/wiki/wiki_base.html
{% extends "base.html" %}
{% block title %}
Djangy Documentation - Djangy: Instant Deployment and scaling for your django applications
{% endblock %}
{% block pagetitle %}
    <div class="page-title">
         <a href="/docs"><h2>Documentation</h2></a>
         <ul class="nav">
             <li><a href="mailto:support@djangy.com">Need help? email support@djangy.com</a></li>
         </ul>
     </div>
{% endblock %}
{% block content %}
<div class="col1">
{% block footer %}{% endblock %}
{% block wiki_content %}{% endblock %}
</div>
<div class="col2">
{{ navbar.content|safe }}
</div>
{% endblock %}